@startuml

!include ../c4/C4_Container.puml

title Диаграмма контейнеров (C4)"

AddRelTag("blue", $textColor="blue", $lineColor="blue")
AddRelTag("green", $textColor="green", $lineColor="green")
AddRelTag("purple", $textColor="purple", $lineColor="purple")



Person_Ext(Клиент, "Клиент", "Хочет открыть депозит")

Person_Ext(ВнешнийСпециалистКолЦентра, "Внешний специалист кол-центра", "Обслуживает клиентов по телефону")


System_Boundary(Банк, "Банк", "Банк") {
Person(Депозит_Бэкофис, "Сотрудник бэк-офиса по депозитам", "Обслуживает депозиты")

Container(Облако, "Облако","YandexCloud", "Хранит актуальные данные ставок по депозитам")

Person(СпециалистКолЦентра, "Специалист кол-центра", "Обслуживает клиентов по телефону")
Container(Система_КолЦентра, "Система кол-центра", "Java", "Система для обслуживания клиентов по телефону")


Container(APIGateway, "Api Gateway","Nginx",  "Проксирует запросы")

System_Boundary(ABCSystem, "ABC", "ABC") {

Container(ABC_Депозиты, "Ядро системы по депозитам","Java",  "Ядро система для работы с депозитами")
Container(ABCDB_Депозиты, "База данных ABC по депозитам ","PostgreSQL",  "Хранит данные по депозитам")
}







Rel(Клиент, "APIGateway", "Создать заявку на депозит")
Rel(Клиент, "ВнешнийСпециалистКолЦентра", "Создать заявку на депозит")
Rel(APIGateway, Система_КолЦентра, "Создать заявку на депозит")
Rel(Система_КолЦентра, ABC_Депозиты, "Получить актуальные данные по ставкам")
Rel_U(ABC_Депозиты, Облако, "Загрузить актуальные данные по ставкам")
Rel(ABC_Депозиты, ABCDB_Депозиты, "Получить актуальные данные по ставкам")
Rel(СпециалистКолЦентра, Система_КолЦентра, "Создать заявку от клинта")
Rel(ВнешнийСпециалистКолЦентра , "Облако", "Получить актуальные данные по ставкам")
Rel(Депозит_Бэкофис, ABC_Депозиты, "Обновить ставки по депозитам")


@enduml